### ISSUE TITLE
Updating from v1.10.0 to v1.10.1 throws "process is not defined" error

### ISSUE THREAD

**Issue by wtachau** [liveblocks/liveblocks#1523]
**Describe the bug**

It seems like, from looking at the diff, [this commit](https://github.com/liveblocks/liveblocks/commit/a848e8b6fbe7deee8dc0d7023a1c9331eb908e31) is breaking our app with the error "process is not defined."

```
@liveblocks_client.js?v=21fbc75a:6692 Uncaught (in promise) ReferenceError: process is not defined
    at getBaseUrl (@liveblocks_client.js?v=21fbc75a:6692:25)
    at createClient (@liveblocks_client.js?v=21fbc75a:6716:19)
```

I know that [the docs](https://liveblocks.io/docs/platform/troubleshooting#process-not-defined) mention this error and say that we should be using a bundler. I am using what I think is a relatively straight-forward setup with SvelteKit/vite, and I still see this. I tried adding `"@liveblocks/client"` to [optimizeDeps](https://vitejs.dev/config/dep-optimization-options#optimizedeps-include) and I still see this error.

At the very least, I would have expected the bump from 1.10.0 to 1.10.1 (a patch version) to mention that this library would no longer work if it wasn't getting bundled.

**Comment by CTNicholas** [comment]
Hey, thanks for leaving the issue! We're looking into it.

**Comment by nvie** [comment]
Thanks for reporting this issue @wtachau. I've just published [1.10.4](https://github.com/liveblocks/liveblocks/releases/tag/v1.10.4) which contains the fix. Sorry about the hassle! Please let us know if you run into any other issues.

**Comment by RenovationIGuess** [comment]
I'm still facing the issue in 1.11.0, is there any updates?
![image](https://github.com/liveblocks/liveblocks/assets/78362896/18c947b1-1e8c-4d61-977c-aadf88781ad4)

**Comment by nvie** [comment]
@RenovationIGuess Thanks for bringing this to our attention. It should now be fixed in [v1.11.1](https://github.com/liveblocks/liveblocks/releases/tag/v1.11.1).
